config/routes.rb
Rails.application.routes.draw do
  resources :attractions
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  belongs_to :location
  has_many_attached :pictures
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :attractions
    has_many_attached :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
    
    @random_attraction = Attraction.all.sample
    # @random_attraction = Attraction.all.sample
    @location = Location.find_by(id: params[:id])
    @correct_location = @location.attractions

  
  end
  # @location = Location.find_by(id: params[:id])
  # @attraction = .find_by(id: params[:id])
  # location = Location.find_by(:name)


#   foreach attraction in Attractions.all
#   if attraction.location == goodLocation
#       goodAttractions << attraction 
#       // push correct attraction into new attraction array
#   end
# end 





  # GET /attractions/1
  # GET /attractions/1.json
  def show
    @attraction = Attraction.find_by(id: params[:id])
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :description, :location_id, pictures: [])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @random_location = Location.all.sample
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find_by(id: params[:id])
  
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :description, pictures: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/attractions/_form.html.erb
<%= simple_form_for(@attraction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.file_field :pictures, multiple: true %>
    <%= f.association :location %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>



<div class="attraction_name">
<div class="d-flex justify-content-center">
<%= @correct_location[0].name %>
</div>
</div>

<div id="img_attraction">
<div class="d-flex justify-content-start">
<%= image_tag @correct_location[0].pictures.first %>
</div>
</div>

<div id="description">
<div class="d-flex justify-content-end">
<%=  @correct_location[0].description %>
</div>
</div>

<div class="btn_feature">
<div id="attraction_btn">
<div class="d-flex justify-content-center">
<%= form_tag attractions_path, :method => :get do %>
  
    <div id="btn_feature">
    <%= link_to locations_path, class: "btn_undo" do %>
    <i class="fas fa-undo"></i>
    <% end %>


    <%= link_to  attractions_path, class: "btn_like" do %>
    <i class="fas fa-thumbs-up"></i>
    <% end %>
    
   
  
    <%= button_tag type: 'submit', class: "btn_dislike" do %>
    <i class="fas fa-thumbs-down"></i>
    <% end %>
    </div>
  
<% end %>
</div>
</div>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.picture %></td>
        <td><%= attraction.location %></td>
        <td><%= link_to 'Show', attraction %></td>
        <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Destroy', attraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attraction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attraction.description %>
</p>

<p>
  <% @attraction.pictures.each do |picture|%>
    <%= image_tag picture %>
    <% end %>
</p>

<p>
  <strong>Location:</strong>
  <%= @attraction.location %>
</p>

<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/ab08371c86.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :pictures, multiple: true %>
    
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>


<div class="location_name">
<div class="d-flex justify-content-center">
<%= @random_location.name%>
</div>
</div>

<div id="img_location">
<div class="d-flex justify-content-start">
<%= image_tag @random_location.pictures.first %>
</div>
</div>


<div id="description_location">
<div class="d-flex justify-content-end">
<%=  @random_location.description %>
</div>
</div>

<div class="btn_feature">
<div id="location_btn">
<div class="d-flex justify-content-center">
<%= form_tag locations_path, :method => :get do %>
  
    <div id="btn_feature">
    <%= link_to locations_path, class: "btn_undo" do %>
    <i class="fas fa-undo"></i>
    <% end %>


    <%= link_to  attractions_path(:id => @random_location), class: "btn_like" do %>
    <i class="fas fa-thumbs-up"></i>
    <% end %>
    
   
  
    <%= button_tag type: 'submit', class: "btn_dislike" do %>
    <i class="fas fa-thumbs-down"></i>
    <% end %>
    </div>
  
<% end %>
</div>
</div>
</div>
    
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.description %></td>
        
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<p>
  <% @location.pictures.each do |picture|%>
    <%= image_tag picture %>
    <% end %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>